attendant/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from . import views

urlpatterns = [
    path('', views.Index, name='index'),
    path('student/<pk>', views.StdDetail_view, name='student-detail'),
    path('todayAbsent', views.Absent_today_View, name='todayAbsent'),
    path('reg_today_absent/<student_id>',
         views.RegNewAbsent_view, name='reg_today_absent'),
    path('upfile/', views.upfile_view, name='upfile'),
    path('students_list/<base>', views.StudentListView, name='StudentListView'),
    path('profile/', views.userprofile_view, name='userprofile'),
    path('likestudent/', views.likeStudent, name='likestudent'),
    path('userdata/', views.userdata, name='userdata')
    # Restful API


]

waw/attendant/urls.py
from django.urls import path

from . import views


#all pattern
urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('student/<pk>', views.StdDetail_view,
         name='student-detail'),
    #path('student_10/<id>', views.StudentListLevel_view),
    path('todayAbsent', views.Absent_today_View, name='todayAbsent'),

    path('reg_today_absent/<student_id>',
         views.RegNewAbsent_view, name='reg_today_absent'),
    path('upfile/', views.upfile_view, name='upfile'),
    path('students_list/', views.StudentListView, name='StudentListView'),
    path('regtodayabsent/', views.AbsentCreatView.as_view(), name='AbsentCreatView'),
    path('profile/', views.userprofile_view, name='userprofile'),
    ]

waw/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('attendant/', include('attendant.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

attendant/models.py
from django.db import models
from django.urls import reverse
import os
#from .settings import BASE_DIR
from django.contrib.auth import get_user_model
User = get_user_model()

#Document_ROOT = os.path.join(BASE_DIR, 'media/document/')


absent_typy_choice = (('n', 'غیبت حضوری'), ('v', 'غیبت مجازی'), ('e', 'غیبت امتحان'), ('d', 'اخراج از کلاس'),
                      ('d', 'تاخیر در کلاس '), ('d', 'فرار از مدرسه'), ('d', 'بی انظباطی'))

level_choice = (('10', 'دهم'), ('11', 'یازدهم'), ('12', 'دوازدهم'))


class School(models.Model):
    id = models.CharField(primary_key=True, max_length=10)
    school_name = models.CharField(max_length=50)
    school_phone = models.CharField(max_length=30)
    school_address = models.CharField(max_length=100)
    studyfield_code_list = models.TextField(
        max_length=120, null=True, blank=True)
    studyfield_name_list = models.TextField(
        max_length=1024, null=True, blank=True)
    school_admin = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    school_sms_api = models.CharField(max_length=120, null=True, blank=True)
    school_sms_username = models.CharField(
        max_length=30, null=True, blank=True)
    school_sms_password = models.CharField(
        max_length=30, null=True, blank=True)

    def __str__(self):
        return self.id

    def get_absolute_url(self):
        return reverse('school_detail', args=[str(self.id)])


class Course(models.Model):
    id = models.CharField(primary_key=True, max_length=10)
    school = school = models.ForeignKey(
        School, on_delete=models.SET_NULL, null=True, blank=True)
    course_name = models.CharField(max_length=50, null=True, blank=True)
    course_level = models.CharField(max_length=2, null=True, blank=True)

    def __str__(self):
        return self.course_name

    def get_absolute_url(self):
        return reverse('school_detail', args=[str(self.id)])


class Student(models.Model):
    id = models.CharField(primary_key=True, max_length=12)
    student_name = models.CharField(max_length=50, null=True, blank=True)
    school = models.ForeignKey(
        School, on_delete=models.SET_NULL, null=True, blank=True)
    studyfield_code = models.CharField(max_length=10, null=True, blank=True)
    studyfield_name = models.CharField(max_length=40, null=True, blank=True)
    input_date = models.DateField(null=True, blank=True)
    parent_mobile = models.CharField(max_length=11)
    student_level = models.CharField(
        max_length=2, choices=level_choice, blank=True, default='10')

    def __str__(self):
        return self.id

    def get_absolute_url(self):
        return reverse('student-detail', args=[str(self.id)])


class Absent(models.Model):
    student = models.ForeignKey('Student', on_delete=models.CASCADE)
    course = models.ForeignKey(
        Course, on_delete=models.SET_NULL, null=True, blank=True)
    absent_date = models.DateField()
    sent = models.BooleanField(default=False)
    absent_type = models.CharField(
        max_length=1, choices=absent_typy_choice, blank=True, default='n')
    absent_detail = models.TextField(
        max_length=512, null=True, blank=True)

    def __str__(self):
        return str(self.absent_date)

    def get_absolute_url(self):
        return reverse('absent-detail', args=[str(self.absent_detail)])


class Like(models.Model):
    student = models.ForeignKey(
        Student, on_delete=models.SET_NULL, null=True, blank=True)
    date_send = models.DateField(null=True, blank=True)


class Document(models.Model):
    docfile = models.FileField(upload_to='documents/%Y/%m/%d')

attendant/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
import datetime
from django.forms import ModelForm
from attendant.models import *


class DocumentForm(forms.Form):
    docfile = forms.FileField(
        label='Select a file',
        help_text='max. 42 megabytes'
    )


class DateInput(forms.DateInput):
    input_type = 'date'


class Sent_to_parent_Form(forms.Form):
    btn = forms.CharField()


class AbsentForm(ModelForm):
    student = forms.CharField(widget=forms.HiddenInput(), required=False)

    def __init__(self, *args, **kwargs):
        super(AbsentForm, self).__init__(*args, **kwargs)

        self.fields['absent_type'].required = True

    class Meta:
        model = Absent
        fields = ['absent_type','course', 'absent_detail']
        labels = {
            "absent_type": "نوع غیبت",
            "course": 'عنوان کلاس',
            "absent_detail": 'شرح بی انظباطی',
        }
        # widgets = {
        #     'absent_date': DateInput(),
        # }

attendant/views.py
import requests
import datetime
import simplejson as json
from django.urls import reverse_lazy
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from attendant import models
from attendant.forms import AbsentForm, DocumentForm, Sent_to_parent_Form
from attendant import date_conversion
from django.views import generic
from django.shortcuts import render


from django.http import JsonResponse


from django.contrib.auth.models import User, Group
from csv import reader

import csv

from django.contrib.auth.models import Permission


def userdata(request):
    with open('attendant/users_file.csv', 'r') as csv_file:
        csvf = reader(csv_file)
        data = []
        for username, password, *__ in csvf:
            u = models.User()
            u.password = 'Abc1234'
            u.is_superuser = "0"
            u.username = username
            u.date_joined = "2018-09-27 05:14:50"
            u.save()
            usr = User.objects.get(username=username)
            permission = Permission.objects.get(name='Can view absent')
            usr.user_permissions.add(permission)
            permission = Permission.objects.get(name='Can view student')
            usr.user_permissions.add(permission)
            my_group = Group.objects.get(name='parents')
            my_group.user_set.add(usr)
            usr.set_password('raw_password')
            usr.save()
            data.append('user :'+username+'is built')
    return render(request, 'attendant/test.html', {'data': data})


# Create your views here.
today = datetime.date.today()
absent_type_help_text = {
    'n': 'غیبت حضوری',
    'v': 'غیبت مجازی',
    'e': 'غیبت امتحان',
    'd': 'اخراج از کلاس',
    'd': 'تاخیر در کلاس ',
    'd': 'فرار از مدرسه',
    'd': 'بی انظباطی',
}


def listToString(s):
    # initialize an empty string
    str1 = ""

    # traverse in the string
    for ele in s:
        str1 += str(ele)

    # return string
    return str1


def get_user_group(request):
    if request.user.groups.filter(name='managers').exists():
        group = 'managers'
    else:
        group = 'parents'
    return group


# Get name and school's student from user who logins


def get_info_of__school(request):
    id_list = []  # students whobelong to the specified school
    uid = request.user.id
    school_id = models.School.objects.filter(school_admin=uid)[0]
    school_name = models.School.objects.filter(
        id=school_id).values_list('school_name')[0]
    school_study_code_list = models.School.objects.filter(
        id=school_id).values_list('studyfield_code_list')[0]
    school_study_name_list = models.School.objects.filter(
        id=school_id).values_list('studyfield_name_list')[0]
    students_list = models.Student.objects.filter(school_id=school_id)
    for std in students_list:
        id_list.append(std.id)
    school_info = {'id_list': id_list, 'school_name': school_name,
                   'school_study_code_list': school_study_code_list,
                   'school_study_name_list': school_study_name_list,
                   }
    return school_info


def Index(request):
    if (get_user_group(request) == 'managers'):
        context = {}
        school_info = get_info_of__school(request)
        n_absent = models.Absent.objects.all().filter(
            student__in=school_info['id_list']).count()
        n_student = models.Student.objects.all().filter(
            id__in=school_info['id_list']).count()
        percent_absent = int((n_absent / (n_student * 50)) * 100)
        context = {'number_student': n_student,
                   'percent_absent': percent_absent,
                   'school_name': school_info['school_name'][0]}
    else:
        context = {'error': 'لطفا با نام کاربری وارد شوید'}
    return render(request, 'attendant/index.html', context)


@login_required()
def StudentListView(request, base=0):
    students_list = []
    if (get_user_group(request) == 'managers'):
        school_info = get_info_of__school(request)
        # Make List studyfields of School by converting string to list
        str_studycode_tuple = ''.join(
            school_info['school_study_code_list'][0])

        str = '[' + str_studycode_tuple + ']'
        jsonDec = json.decoder.JSONDecoder()
        StudyFieldCode_list = jsonDec.decode(str)
        StudyFieldName_list = (
            school_info['school_study_name_list'][0]).split(",")
        # Pair of code and name of field Convert to a dictionary.
        zip_iterator = zip(StudyFieldCode_list, StudyFieldName_list)
        dict_studyfields = dict(zip_iterator)
        # If the manager go to filters
        if request.method == 'POST':
            filter_field = (request.POST['filter_field'])
            filter_base = (request.POST['filter_base'])
            students_list = models.Student.objects.filter(
                id__in=school_info['id_list']).filter(
                student_level=filter_base).filter(
                studyfield_code=filter_field)

        else:  # all Student are listed for by base 0
            if base == '0':
                students_list = models.Student.objects.filter(
                    id__in=school_info['id_list'])
            else:  # If linke base in html page clicked
                students_list = models.Student.objects.filter(
                    id__in=school_info['id_list']).filter(student_level=base)
    else:
        # Parents username is p plus ID that p is deleted to set the ID
        uname = request.user.username[1:11]
        students_list = list(models.Student.objects.filter(id=uname))
    context = {'students_list': students_list,
               'fieldcode_list': dict_studyfields
               }
    return render(request, 'attendant/students_list.html', context)


@login_required()
def StdDetail_view(request, pk):
    # if student ID is fake handle it
    absent_tuple_info = ()
    dict = {}
    counter = 0

    std = models.Student.objects.get(pk=pk)

    absents = list(models.Absent.objects.filter(student=pk))
    if absents:
        absent_tuple_info = date_conversion.to_persion_date(absents)
    dict = {'parent_mobile': std.parent_mobile,
            'absent_tuple_info': absent_tuple_info,
            'len': len(absent_tuple_info),
            'student_id': pk,
            'absent_type_help_text': absent_type_help_text}
    return render(request, 'attendant/student_detail.html', dict)


"""
    Report for absent
"""


@login_required()
def Absent_today_View(request):
    yesterday = today - datetime.timedelta(days=1)
    absent_tuple_info = ()

    # Go to specific school with find school_id value
    if (get_user_group(request) == 'managers'):
        school_info = get_info_of__school(request)

    today_list = models.Absent.objects.filter(
        absent_date=today).filter(student__in=school_info['id_list']).filter(sent=False)

    yesterday_list = models.Absent.objects.filter(
        absent_date=yesterday).filter(student__in=school_info['id_list'])

    all_days = models.Absent.objects.all().filter(
        student__in=school_info['id_list'])
    absent_tuple_info = date_conversion.to_persion_date(all_days)

    x = datetime.datetime.now()
    present = date_conversion.gregorian_to_jalali(x.year, x.month, x.day)

    test_button_name = 'No'
    # Save parent_phone to a list for sending SMS
    dict = {'absent_today_list': today_list,
            'absent_yesterday_list': yesterday_list,
            'absent_type_help_text': absent_type_help_text,
            'absent_tuple_info': absent_tuple_info,
            'len': len(absent_tuple_info),
            'today_is': present}
    return render(request, 'attendant/absent_detail.html', dict)


"""
    Send SMS to parent
"""


def likeStudent(request):
    if request.method == 'GET':
        data_text = request.GET['data_text']
        # convert to list that [0] is student_id and [1] is absent_id
        data_list = data_text.split(",")
        # Make prameters for SMS
        student_id = data_list[0]
        absent_id = data_list[1]
        x = datetime.datetime.now()
        perion_date = date_conversion.gregorian_to_jalali(
            x.year, x.month, x.day)

        absent_type = models.Absent.objects.filter(
            id=absent_id).values_list("absent_type")[0]
        # get absent_type for making SMS
        sms = "هنرستان جابر این حیان:سلام والدین گرامی " + "فرزند شما در تاریخ " + \
              listToString(perion_date) + " " + " " + \
              absent_type_help_text[absent_type[0]] + " " + " داشته است"

        likedstudent = models.Student.objects.get(
            pk=student_id)  # getting the liked student
        payload = {'Username': 'jaberedu', 'Password': '36318513',
                   'From': '-1', 'To': likedstudent.parent_mobile, 'Text': sms}
        r = requests.post(
            'https://www.payam-resan.com/APISend.aspx', params=payload)
        # Creating Like Object
        m = models.Like(student=likedstudent, date_send=today)
        m.save()  # saving it to store in database

        # Flag sent of Absent object True
        m = models.Absent.objects.get(id=absent_id)
        m.sent = True
        m.save()
        # Sending an success response
        return HttpResponse(r)
    else:
        return HttpResponse("Request method is not a GET")


# list Student using Ajax in template


def LoadStudentFromBase(request):
    pass


@login_required()
def RegTodayAbsent_view(request, student_id):
    # if student ID is fake handle it
    absent_date_list = []
    try:
        std = models.Student.objects.get(pk=student_id)
        absent_list = list(models.Absent.objects.filter(
            student=student_id).values_list('absent_type', 'absent_date'))
        dict = {'parent_mobile': std.parent_mobile,
                'absent_list': absent_list,
                'student_id': student_id}
    except std.DoesNotExist:

attendant/templates/attendant/absent_detail.html
{% extends "attendant/base_generic.html" %}

{% block content %}

<p id="message"></p>
  <p>  <strong>  لیست غیبت ها ی امروز: </strong></p>
  <h3>{{today_is}}  : تاریخ </h3>
  {% if absent_today_list %}
  <table class="table_style">
  <tr>
    <th>ردیف</th>
    <th>نوع غیبت</th>
    <th>کد ملی</th>
    <th>نام و نام خانوادگی</th>
    <th>ارسال پیام</th>
  </tr>
    {% for absent in absent_today_list %}
  <tr>
    <td><strong>{{ forloop.counter }} </strong></td>
    <td>{% for key, value in absent_type_help_text.items %}
      {% ifequal absent.absent_type  key %}
        {{ value }}
      {% endifequal %}
    {% endfor %}
  </td>
    <td><a href="{{ absent.student.get_absolute_url }}">{{ absent.student}}</a></td>
    <td>{{ absent.student.student_name}}</td>
    <td>
      <a class="likebutton" id="like{{absent.student}}" href="#" studentid_absentid="{{absent.student}},{{absent.id}}">ارسال</a>
    </td>
  </tr>
    {% endfor %}

  </table>
  {% endif %}
  <hr/>
  <p><strong>لیست غیبت ها ی دیروز: </strong></p>

  {% if absent_yesterday_list %}

  <table class="table_style">
  <tr>
    <th>ردیف</th>
    <th>نوع غیبت</th>
    <th>کد ملی</th>
  </tr>
    {% for absent in absent_yesterday_list %}
  <tr>
    <td><strong>{{ forloop.counter }} </strong></td>
    <td>
      {% for key, value in absent_type_help_text.items %}
        {% ifequal absent.absent_type  key %}
          {{ value }}
        {% endifequal %}
      {% endfor %}
      </td>
    <td><a href="{{ absent.student.get_absolute_url }}">{{ absent.student}}</a></td>
  </tr>
    {% endfor %}
  </table>
  {% endif %}
  <hr/>
  <p>لیست همه غیبت ها : </p>
  <table class="table_style">
  <tr>
    <th>ردیف</th>
    <th>تاریخ</th>
    <th>نوع غیبت</th>
  </tr>
  {% for val in absent_tuple_info %}
  <tr>
    <td><strong>{{ forloop.counter }} </strong></td>
    <td>{{ val.0 }}</td>
    <td>{% for key, value in absent_type_help_text.items %}
      {% ifequal val.1  key %}
        {{ value }}
      {% endifequal %}
    {% endfor %}
  </td>
  </tr>
  {% endfor %}
  </table>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script type="text/javascript">
  $('.likebutton').click(function(){
  var catid;
  studentid_absentid = $(this).attr("studentid_absentid");
  $.ajax(
  {
      type:"GET",
      url: "likestudent/",
      data:{
               data_text : studentid_absentid
      },
      success: function( data )
      {
          $( '#like'+ studentid_absentid ).remove();
          $( '#message' ).text(data);
      }
   })
  });
  </script>
{% endblock %}

attendant/templates/attendant/absent_form.html
{% extends "attendant/base_generic.html" %}

{% block content %}

{% if perms.attendant.add_absent %}
  {% if id %}
<div class="form_container">
    <p class="p_id">کدملی : {{ id }}</p>
  {% endif %}
  <form action="" method="post">
      {% csrf_token %}
      <table>
      {{ form.as_p }}
      </table>
      
      <input type="submit" value="ثبت" />

  </form>
</div>
{% endif %}
{% endblock %}

attendant/templates/attendant/absent_report.html
{% extends "attendant/base_generic.html" %}

{% block content %}

<p id="message"></p>
  <p>  <strong>  لیست غیبت ها ی امروز: </strong></p>
  <h3>{{today_is}}  : تاریخ </h3>
  {% if absent_today_list %}
  <table class="table_style">
  <tr>
    <th>ردیف</th>
    <th>نوع غیبت</th>
    <th>کد ملی</th>
    <th>نام و نام خانوادگی</th>
    <th>ارسال پیام</th>
  </tr>
    {% for absent in absent_today_list %}
  <tr>
    <td><strong>{{ forloop.counter }} </strong></td>
    <td>{% for key, value in absent_type_help_text.items %}
      {% ifequal absent.absent_type  key %}
        {{ value }}
      {% endifequal %}
    {% endfor %}
  </td>
    <td><a href="{{ absent.student.get_absolute_url }}">{{ absent.student}}</a></td>
    <td>{{ absent.student.student_name}}</td>
    <td>
      <a class="likebutton" id="like{{absent.student}}" href="#" studentid_absentid="{{absent.student}},{{absent.id}}">ارسال</a>
    </td>
  </tr>
    {% endfor %}

  </table>
  {% endif %}
  <hr/>
  <p><strong>لیست غیبت ها ی دیروز: </strong></p>

  {% if absent_yesterday_list %}

  <table class="table_style">
  <tr>
    <th>ردیف</th>
    <th>نوع غیبت</th>
    <th>کد ملی</th>
  </tr>
    {% for absent in absent_yesterday_list %}
  <tr>
    <td><strong>{{ forloop.counter }} </strong></td>
    <td>
      {% for key, value in absent_type_help_text.items %}
        {% ifequal absent.absent_type  key %}
          {{ value }}
        {% endifequal %}
      {% endfor %}
      </td>
    <td><a href="{{ absent.student.get_absolute_url }}">{{ absent.student}}</a></td>
  </tr>
    {% endfor %}
  </table>
  {% endif %}
  <hr/>
  <p>لیست همه غیبت ها : </p>
  <table class="table_style">
  <tr>
    <th>ردیف</th>
    <th>تاریخ</th>
    <th>نوع غیبت</th>
  </tr>
  {% for val in absent_tuple_info %}
  <tr>
    <td><strong>{{ forloop.counter }} </strong></td>
    <td><a href="{{ absent.get_absolute_url }}"> جزپیات</a></td>
    <td>{{ val.0 }}</td>
    <td>{% for key, value in absent_type_help_text.items %}
      {% ifequal val.1  key %}
        {{ value }}
      {% endifequal %}
    {% endfor %}
  </td>
  </tr>
  {% endfor %}
  </table>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script type="text/javascript">
  $('.likebutton').click(function(){
  var catid;
  studentid_absentid = $(this).attr("studentid_absentid");
  $.ajax(
  {
      type:"GET",
      url: "likestudent/",
      data:{
               data_text : studentid_absentid
      },
      success: function( data )
      {
          $( '#like'+ studentid_absentid ).remove();
          $( '#message' ).text(data);
      }
   })
  });
  </script>
{% endblock %}

attendant/templates/attendant/base_generic.html
<!DOCTYPE html>
<html lang="fa">
<head>

  {% block title %}<title>سیسنم انظباطی واو</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">


</head>
<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <header class="avatar">
		<img src="../media/majid228.jpg" />
    <h4>{{ user.get_username }}</h4>
  </header>
      <ul class="sidebar-nav">
          <li><a href="/attendant">صفحه نخست</a></li>
          <li><a href="/admin">صفحه مدیر</a></li>
          <li><a href="{% url 'StudentListView' base=0 %}">همه دانش آموزان</a></li>
          <li><a href="{% url 'todayAbsent' %}">همه غیبت ها</a></li>
          {% if user.is_authenticated %}
             <li><a href="{% url 'logout'%}?next={{request.path}}">خروج</a></li>
          {% else %}
             <li><a href="{% url 'login'%}?next={{request.path}}">ورود</a></li>
          {% endif %}
  </ul>
      </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
      </div>
    </div>

  </div>
</body>
</html>

attendant/templates/attendant/ceate_absent.html
{% extends "attendant/base_generic.html" %}

{% block content %}

<form action="/new-absent/" method="post">
    {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="Submit">
</form>
{% endblock %}

attendant/templates/attendant/index.html
{% extends "attendant/base_generic.html" %}

{% block content %}
{{study_test}}
<h1>WAW</h1>

  <p style="font-family:ِYekan">خوش آمدید - سیستم مدیریت موارد انطباطی دانش آموزان <strong>واو</strong></p>

<h2>نام مدرسه</h2>
  {% if error %}
    <h3>{{ error}}</h3>
  {% else %}
    <h3>{{ school_name}}</h3>
    <table class="table_style">
    <tr>
      <th>تعداد دانش آموز</th>
      <th>درصد غیبت ها</th>
    </tr>
    <tr>

      <td>{{ number_student }}</td>
      <td>{{ percent_absent }}%</td>
    </tr>
    </table>
  {% endif %}
{% endblock %}

attendant/templates/attendant/login_error.html
{% extends "attendant/base_generic.html" %}

{% block content %}
    <h1>Error Login</h1>
{% endblock %}

attendant/templates/attendant/sms_result.html
{{ pmobile}}
{{ result }}
{{phone}}
{{test}}

attendant/templates/attendant/student_detail.html
{% extends "attendant/base_generic.html" %}

{% block content %}

  <hr/>
    {{username}}
  <p>شماره موبایل والدین :  <strong><br/>{{ parent_mobile }}</strong> </p>

  <p>لیست غیبت ها : </p>
  {{absents}}
  <table class="table_style">
  <tr>
    <th>ردیف</th>
    <th>تاریخ</th>
    <th>نوع غیبت</th>
  </tr>
  {% for val in absent_tuple_info %}
  <tr>
    <td><strong>{{ forloop.counter }} </strong></td>
    <td>{{ val.0 }}</td>
    <td>{% for key, value in absent_type_help_text.items %}
      {% ifequal val.1  key %}
        {{ value }}
      {% endifequal %}
    {% endfor %}</td>
  </tr>
  {% endfor %}
  </table>
{% ifequal user.groups.all.0.name "managers" %}
<br/>
<h3><a href="{% url 'reg_today_absent' student_id %}">ثبت غیبت</a></h3>
{% endifequal %}



<hr>
  <div style="margin-left:20px;margin-top:20px">

  </div>


{% endblock %}

attendant/templates/attendant/student_detail_old.html
{% extends "attendant/base_generic.html" %}

{% block content %}
  <h1>کد ملی: {{ student.id }} </h1>
  <hr/>
  <p><strong>شماره والدین:</strong> {{ student.parent_mobile }}</p>

  <p><strong>Absents number : {{ std }}:</strong> </p>
  <p></p>
  <p><a href="">لیست غیبت ها : </a></p>
<hr>
  <div style="margin-left:20px;margin-top:20px">

  </div>
{% endblock %}

attendant/templates/attendant/students_list_with_level.html
{% extends "attendant/base_generic.html" %}

{% block content %}
    <h1>Students List</h1>

    {% if student_list_level %}
    <ul>

      {% for student in student_list_level %}
      <li>
        <a href="{{ student.get_absolute_url }}">    {{ student.id }}</a> {{student.parent_mobile}})
      </li>
      {% endfor %}
    </ul>
    {% else %}}
      <p>There are no students.</p>
    {% endif %}

{% endblock %}